# Generated by Django 5.0.7 on 2024-07-24 23:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General Chat Room', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='No content')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(default='Anonymous', max_length=255)),
                ('room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Vortex_chat_app.chatroom')),
            ],
        ),
    ]
